// Code generated by "stringer -type=MMModem3gppPacketServiceState -trimprefix=MmModem3gppPacketServiceState"; DO NOT EDIT.

package modemmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MmModem3gppPacketServiceStateUnknown-0]
	_ = x[MmModem3gppPacketServiceStateDetached-1]
	_ = x[MmModem3gppPacketServiceStateAttached-2]
}

const _MMModem3gppPacketServiceState_name = "UnknownDetachedAttached"

var _MMModem3gppPacketServiceState_index = [...]uint8{0, 7, 15, 23}

func (i MMModem3gppPacketServiceState) String() string {
	if i >= MMModem3gppPacketServiceState(len(_MMModem3gppPacketServiceState_index)-1) {
		return "MMModem3gppPacketServiceState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MMModem3gppPacketServiceState_name[_MMModem3gppPacketServiceState_index[i]:_MMModem3gppPacketServiceState_index[i+1]]
}
